### ISSUE TITLE
Suspicious certificate results not showing in results.txt

### ISSUE THREAD

**Issue by arthurblabla** [atenreiro/opensquat#50]
**Is your feature request related to a problem? Please describe.**
When I run opensquat on my keywords with the command below, event if it finds "suspicious certificate"  in the "Checking Domain Squatting" section, I have nothing written in results.txt. Maybe I missed something, but is there a way to have this results written somewhere ?

`python3 opensquat.py --phishing phishing_domains.txt --dns --ct --subdomains --portcheck -c 4 --vt -p month
`

Many thanks for your great tool

**Comment by atenreiro** [comment]
Hello!

You are right, the certificate transparency (CT) is not being saved in the results.txt simply because I never developed this feature and prioritize others.

If this is important to you I can add it in the next release?

**Comment by arthurblabla** [comment]
Hello,

It would be great ! I think it's a great feature, I would love to have these results in the output.
Thanks you very much !

**Comment by bigverm23** [comment]
any update on this?

**Comment by atenreiro** [comment]
Hey @arthurblabla @bigverm23 

This fell out of my radar. I have committed a latest version v.199 - see if it fixes the problem. 

`python3 opensquat.py --ct`

**Comment by bigverm23** [comment]
where are the results supposed to be stored?

**Comment by bigverm23** [comment]
![image](https://user-images.githubusercontent.com/17554438/169663862-9472c485-9b34-45f8-bb4b-1713d9833d03.png)

it's saying it's finding suspicious certs but they dont show up in results

**Comment by bigverm23** [comment]
ah I see.  running with opensquat.py --dns --ct gives results. 

running with opensquat.py --phishing phishing_domains.txt --dns --ct --subdomains --portcheck does not produce results.

**Comment by prathamxx** [comment]
Hello i see that the result is still not showing in results.txt, thus we have came up with another command to run to resolve the issue.

python3 opensquat.py --phishing phishing_domains.txt --dns --ct --subdomains --portcheck -c 4 --vt -p month >> results.txt
We hope it helps.
